Task 13 4
andzia0520/anna-wierzejska-kodilla-java pull request #36
Opened 2020-10-06 19:04 UTC by andzia0520

2020-11-23 16:16 UTC, marszelun requested changes

2020-11-23 16:16 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/infoRetrieving/OrderRetriever.java
> +        Product flour = new Product("flour", 2.95, healthyShop);
Hmm, po co tworzysz tyle produktów, skoro niżej wykorzystujesz tylko 2?

2020-11-23 16:16 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/infoRetrieving/SupplierExtraFoodShop.java
> +    public void process(Order order) {
Skąd będzie wiadomo, że proces zamawiania u tego dostawcy się nie powiódł? Są przynajmniej 2 możliwości:
- zwracanie `boolean` lub innego obiektu ze statusem,
- rzucenie wyjątku w przypadku błędu zamawiania u tego dostawcy.
(analogiczna uwaga dla pozostałych dostawców).

2020-11-23 16:16 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/notification/InformationService.java
> +    void inform(Supplier supplier);
Tu raczej chodzi o informowanie klienta (np. o przyjęciu zamówienia do realizacji). Dostawcy raczej nie trzeba informować, skoro składasz u niego bezpośrednio zamówienie przez API :)

2020-11-23 16:16 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/order/Order.java
> +    private final Supplier supplier;
Tutaj fundamentalnie się nie zgadzam. `Supplier` jest przypisany do produktu, w jednym zamówieniu możesz mieć produkty od wielu różnych dostawców, więc pole typu `Supplier` dla całego zamówienia jest bardzo mylące.

2020-11-23 16:16 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/Application.java
> +        order.getSupplier().process(order);
1. Produkty z zamówienia `order` powinny być w jakiś sposób pogrupowane po dostawcach i dla każdego z nich (dostawców) powinno być przeprocesowane zamówienie produktów tylko od tego dostawcy. 
2. Wszystko to powinno dziać się wewnątrz `orderProcessor`. Ta klasa powinna przykrywać całą złożoność związaną z różnorodnymi systemami dla dostawców, występującymi pod spodem.
3. Do rozważenia też, jak ma się zachować system w przypadku problemu z zamówieniem od jednego lub więcej dostawców. Czy wtedy chcesz anulować całe zamówienie, czy złożyć zamówienie niekompletne? To powinno mieć odzwierciedlenie w obiekcie zwracanym z `orderProcessor`-a.

2020-11-27 17:52 UTC, marszelun requested changes

2020-11-27 17:52 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/Application.java
> +        OrderService service = new OrderService(new MailInfo(), new OrdersRepository(), processor);
Nie musisz tworzyć zmiennej `processor` - od razu tutaj mogłaś użyć `new ...`

2020-11-27 17:52 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/Application.java
> +        service.execute(order);
Przydałby się konkretniejsza nazwa metody, np. `.order(...)` zamiast `.execute(...)`

2020-11-27 17:52 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/database/Repository.java
> +    void saveOrdersHistory(Order order);
Czemu ta metoda się tak nazywa? Zapisujesz jakąś historię? Przecież zapisujesz pojedyncze zamówienie...

2020-11-27 17:52 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/infoRetrieving/Customer.java
> +    private final String Email;
Nazwa pola z wielkiej litery.

2020-11-27 17:52 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/infoRetrieving/Product.java
> +    private final double price;
Do reprezentacji cen nie używamy liczb zmiennoprzecinkowych! Na tym etapie znajomości Javy powinnaś użyć typu `BigDecimal`.

2020-11-27 18:05 UTC, andzia0520 commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/Application.java
> +        OrderService service = new OrderService(new MailInfo(), new OrdersRepository(), processor);
tak nawet wizualnie lepiej będzie

2020-11-27 18:06 UTC, andzia0520 commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/Application.java
> +        service.execute(order);
nie chciałam powtarzać słowa order

2020-11-27 18:07 UTC, andzia0520 commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/database/Repository.java
> +    void saveOrdersHistory(Order order);
skojarzyłam zapisane w bazie ordery  z historią zamówień

2020-11-27 18:08 UTC, andzia0520 commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/infoRetrieving/Customer.java
> +    private final String Email;
wypadek przy pracy ;/

2020-11-27 18:18 UTC, andzia0520 commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/infoRetrieving/Product.java
> +    private final double price;
zgadzam się

2020-11-28 07:11 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/database/Repository.java
> +    void saveOrdersHistory(Order order);
Ma sens, tylko wtedy raczej klasa powinna się nazywać np. `OrdersHistoryRepository` (bo przechowuje historię zamówień), a podczas zapisu nadal zapisujesz tylko jeden `order` :)

2020-11-28 07:12 UTC, marszelun approved these changes

2020-11-28 10:03 UTC, merged