Task 13 5
andzia0520/anna-wierzejska-kodilla-java pull request #37
Opened 2020-11-18 22:07 UTC by andzia0520

2020-11-20 16:36 UTC, andzia0520 commented
- zastosowanie wzorca Singleton
- dodanie klasy ConnectingFligt
- dodanie do wyszukiwarki metody wyszukującej lot z 1 przesiadką

2020-11-20 19:00 UTC, marszelun requested changes

2020-11-20 19:00 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/Application.java
> +        System.out.println(qtyD);
Fajniej byłoby wyświetlić znalezione loty jako całe obiekty, a nie tylko ich ilości. Możesz w tym celu odpowiednio przeciążyć metodę `toString` w klasie `ConnectingFlight`.

2020-11-20 19:00 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/Db/ConnectionDb.java
> +        if (connectionDbInstance == null) {
Jeśli korzystasz z takiej implementacji singletona, powinnać użyć synchronizacji, aby zapobiec ryzyku wielokrotnego utworzenia instancji w przypadku współbieżnych odpytań metody `getInstance()`.
Tutaj możesz zrobić prościej:
```
private static ConnectionDb instance = new ConnectionDb();
public static ConnectionDb getInstance() {
   return instance;
}
private ConnectionDb() {
 ...
}
``` 
Jeszcze prościej, możesz w ogóle nie używać singletona, tylko:
- stworzyć prywatny, pusty konstuktor (aby zapobiec tworzeniu instancji obiektów),
- zainicjować listę połączeń w statycznym bloku inicjującym,
- stworzyć statyczną, publiczną metodą zwracającą utworzoną tam tablicę:
```
private ConnectionDb() {}
private static final List<Connection> connections = new ArrayList<>();
static {
    connections.add(...)
    ...
}
public static getConnections() {
    return connections;
}
```

2020-11-20 19:00 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/Db/ConnectionDb.java
> +        return connections;
Dobrze byłoby w tej metodzie zwracać kopię tablicy (np. `new ArrayList<>(connections)`) - w przeciwnym przypadku (tak jak teraz), ktoś może zmodyfikować listę połączeń dodając coś do listy, i dla kolejnych wywołań `getConnections()` będziesz dostawać  zmodyfikowaną listę.

2020-11-20 19:00 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/infoRetrieving/Arrival.java
> +public class Arrival {
Rozmawialiśmy na video, że nie jest zasadne utrzymywanie dwóch odrębnych klas `Arrival` i `Departure`. To jest po prostu lotnisko...

2020-11-20 19:00 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/infoRetrieving/ConnectingFlight.java
> +    Departure departure;
Potrzebujesz `departure` i `arrival` jako odrębnych pól?
`depature` zawsze będzie lotniskiem `departure` pierwszego z `connectingFlights`.
`arrival` zawsze będzie lotniskiem `arrival` ostatniego z `connectingFlights`.

2020-11-20 19:00 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/infoRetrieving/ConnectingFlight.java
> +        return connectingFlights.hashCode();
Ciekawa implementacja `hashCode`, nieuzględniająca pól `departure` i `arrival`. Celowo, czy przez przypadek?

2020-11-20 19:00 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/infoRetrieving/ConnectingFlight.java
> +    List<Connection> connectingFlights;
Czemu pola są package-private? Zapamiętaj: `private final` + gettery. To dobra praktyka, przyzwyczaja do tworzenia niemutowalnych obiektów.

2020-11-20 19:00 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/infoRetrieving/Connection.java
> +    Departure departure;
Gdyby była jedna klasa `Airport`:
```
private final Airport departure;
private final Airport arrival;
```

2020-11-20 19:00 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/infoRetrieving/ConnectingFlight.java
> +public class ConnectingFlight {
Proponuję podejść do tego uniwersalnie i nazwać klasę po prostu `Flight` oraz zaprojektować ją tak, żeby była w stanie wyrazić zarówno lot bezpośredni, jak i z przesiadkami.

2020-11-20 19:00 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/searching/SearchingService.java
> +    public List<Connection> findFlightsFromCity(Departure departure) {
Zgodnie z inną uwagą z tego PR, proponuję uniwersalną klasę `Flight` i wtedy wszystkie 3 metody mogłyby zwracać `List<Flight>`.

2020-11-20 19:00 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/searching/SearchingService.java
> +                    oneStopFlights.add(new ConnectingFlight(start.getDeparture(), end.getArrival()));
Fajnie, bo prosto i przejrzyście :)
Teraz utrudnijmy sobie życie i zgodnie z treścią zadania, spróbuj napisać to samo w oparciu o `stream` ;)

2020-11-20 19:00 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/orderService/Application.java
> +public class Application {
Tu i niżej - są zmiany z innnego zadania. Nie powinny być w tym PR.

2020-11-23 10:58 UTC, andzia0520 commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/infoRetrieving/ConnectingFlight.java
> +        return connectingFlights.hashCode();
przez przypadek

2020-11-23 20:37 UTC, andzia0520 commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/Application.java
> +        System.out.println(qtyD);
zgadzam się

2020-11-23 20:38 UTC, andzia0520 commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/Db/ConnectionDb.java
> +        if (connectionDbInstance == null) {
Zastosuję Singleton z synchronizacją

2020-11-23 20:38 UTC, andzia0520 commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/infoRetrieving/ConnectingFlight.java
> +    List<Connection> connectingFlights;
zapamiętam

2020-11-23 20:39 UTC, andzia0520 commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/searching/SearchingService.java
> +                    oneStopFlights.add(new ConnectingFlight(start.getDeparture(), end.getArrival()));
poprawione

2020-11-24 16:26 UTC, marszelun requested changes
Mam poczucie, że przeszłaś z jednej skrajności w drugą. 
Teraz klasa `Flight` próbuje jednocześnie być reprezentacją lotu w bazie, jak i wyniku wyszukiwania.
Żeby trochę pomóc, proponuję stworzenie trzech klas i zbudowanie całej reszty o nie (podaję tylko pola w klasach, wiadomo że muszą mieć konstruktory, gettery, equals+hashCode itd.)
```
class Flight {
    //reprezentuje konkretny lot w siatce połączeń przewoźnika lub lotniska
    private final String from;
    private final String to;
    private final String airline;
    private final String flightNumber;
}

class FlightSearchRequest {
    //reprezentuje żądanie użytkownika, czyli co wpisał w wyszukiwarkę
    private final String departure; //null jeśli dowolne lotnisko z
    private final String arrival; //null jeśli dowolne lotnisko na
    private final boolean connectingFlightsPossible; //true jeśli dopuszczalne przesiadki
}

class FlightSearchResult {
    //reprezentuje jeden wynik zwrócony przez wyszukiwarkę lotów
    private List<Flight>; //lista lotów składających się na jeden wynik; jeśli ma długość 1 - to jest to lot bezpośredni, jeśli 2 lub więcej - to jest to lot z przesiadkami 
}
```
Mając klasę `FlightSearchRequest`, możesz nawet stworzyć jedną metodę `findFlights()` w `SearchingService` i dopiero wewnątrz niej rozdzielić się na 3 obecne metody (wszystkie lotniska z, wszystkie lotniska na, lotnisko z przesiadkami).
Przykładowe wywołanie z `main`:
```
findFlights(new FlightSearchRequest("Warsaw", null, false); //wyszukaj wszystkie loty bezpośrednie z Warszawy
findFlights(new FlightSearchRequest(null, "Gdańsk", false); //wyszukaj wszystkie loty bezpośrednie do Gdańska
findFlights(new FlightSearchReuest("Warsaw", "New York", true); //wyszukaj wszystkie loty (uwzlęgniając łączone) z Warszawy do Nowego Jorku.
```

2020-11-24 16:26 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/Db/FlightsDb.java
> +public class FlightsDb {
Lepiej, ale nadal uważam, że singleton jest tu trochę przekombinowany. Wystarczy pole statyczne, statyczny blok inicjalizujący i statyczny getter :) Ostateczny wybór pozostawiam Tobie.

2020-11-24 16:26 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/searching/SearchingService.java
> +    public List<Flight> findOneStopFlight(String departure, String arrival) {
Klasa `Flight` zawiera wyłącznie `departure` i `arrival`. Nie da się przy jej pomocy przedstawić lotu z przesiadką. Widzę, że z tej metody zwracasz listę `Flight`, czyli poszczególne "segmenty" jednego złożonego lotu są odrębnymi obiektami w tej liście, należącymi do jednego wyniku wyszukiwania.
Dla kontrastu, w dwóch powyższych metodach jeden obiekt na liście to jeden wynik wyszukiwania.
To jest mocno niekonsekwentne podejście - klasa `Flight` nie ma precyzyjnie zdefiniowanej odpowiedzialności i jest używana w dwóch niekompatybilnych kontekstach.

2020-11-24 16:26 UTC, marszelun commented on kodilla-good-patterns/src/test/java/com/kodilla/good/patterns/challenges/flightSearchEngine/SearchingServiceTestSuite.java
> +/*
Czy na pewno chciałaś w PR mieć zakomentowany test?

2020-11-28 11:43 UTC, marszelun requested changes

2020-11-28 11:43 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/SearchingService.java
> +    public FlightSearchResult findFlights(FlightSearchRequest flightSearchRequest) {
Tu się jeszcze nie do końca zrozumieliśmy. Metoda `findFlights` powinna zwracać `List<FlightSearchResult>`.
Przykładowo, zapytanie o wszystkie loty z Warszawy może zwrócić:
- Warszawa -> Poznań (jeden obiekt `FlightSearchResult, w nim lista 1-el.`)
- Warszawa -> Paryż  (jeden obiekt `FlightSearchResult, w nim lista 1-el.`)
Zapytanie o wszystkie loty z Warszawy do Nowego Jorku z przesiadką, może zwrócić:
- Warszawa -> Amsterdam -> Nowy Jork  (jeden obiekt `FlightSearchResult, w nim lista 2-el.`)
- Warszawa -> Madryt -> Nowy Jork  (jeden obiekt `FlightSearchResult, w nim lista 2-el.`)

2020-11-28 11:43 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/flightSearchEngine/SearchingService.java
> +        if (flightSearchRequest.getArrival() == null && !flightSearchRequest.isConnectingFlightsPossible()) {
Takie długie metody są mało czytelne, najlepiej mieć 3 metody prywatne i na podstawie warunku na argumentach wejściowych wywołać właściwą metodę prywatną.

2020-12-04 16:25 UTC, marszelun approved these changes

2020-12-04 16:25 UTC, marszelun commented on kodilla-good-patterns/src/test/java/com/kodilla/good/patterns/challenges/flightSearchEngine/SearchingServiceTestSuite.java
> +public class SearchingServiceTestSuite {
Zakomentowany test.... hmm... a mógłby być odkomentowany i poprawiony :D ?

2020-12-04 21:00 UTC, merged